### PR TITLE
Feature/markdown code block syntax highlighting

### PR DESCRIPTION
**Pull request by jonsherrard**
Hello there!

## Syntax Highlighting

This PR adds the [Shiki syntax highlighter](https://shiki.matsu.io/) to fenced code blocks in MDX files.

Screenshot 2020-04-29 at 22 46 30

This is really neat because all of the syntax processing is done at build time, so there's no need for any extra JS. :)

### Syntax Theme Configuration

I have modified the `gatsby-config.js` to export a function that expects the users's site config as an argument. This enables user-land configuration of the Shiki syntax highlighting theme. I added notes to both the `readme.md` files on how to configure this in the plugin options.

## A note on Prettier.

https://prettier.io/ is a pretty widespread tool in the JS community and I have it enabled by default in my text editor, so it auto-ran-rampant on some formatting.

I've added a `.prettierrc` which for the most part keeps the formatting the same if a Prettier user every contributes to this repo.

One caveat: I could not turn Prettier off from running inside the fenced code blocks. I don't know if that is a blocking issue - I'll have to do some serious burrowing to try and turn it off. Maybe it's OK?

Or I can remove the Prettier element altogether.

Thank you again for this awesome theme. I've been putting together a help center for my team all day, and people love it, and have been contributing documentation already!

Jon

(P.S - Fixes https://github.com/mlent/gatsby-theme-help-center/issues/4)

### CODE REVIEW

**Comment by mlent** [comment]
Looks great at a quick glance, I'll try it myself later today.

And yeah actually I forgot to add prettier, this code is extracted from a monorepo of mine that has prettier in the root directory so i forgot to add it. Thanks for adding this too.

**Comment by mlent** [comment]
(Tiny update on this @jonsherrard I've put it on my schedule for Thursday to merge and release. I want to also try if it's possible to customize the syntax highlighting to match the theme colors a bit more. Just wanted to make sure you're not left hanging as I'm working on multiple projects. Cheers!)

**Comment by jonsherrard** [comment]
Hi @mlent!

Thank you for the update that's very courteous of you! 

No rush on my side I'm maintaining a fork now as there's a couple of other features I've added (layout support for 2,4,6, categories, noIndex, sorting by date or priority, and some other layout nits).

Shiki does accept custom highlighting, but the gatsby plugin does not expose that API. Shiki is abstracted away "under" remark plugins, and MDX layer, and Gatsby itself. So I don't think it's possible to pass in your theme values, nor can I imagine how one would write a M-UI theme -> shiki theme piece of code.

There is styling on the `code` tag `background(0,0,0, 0.8)` or similar, that gets applied to the shiki themes and makes things look a bit off (every Shiki Theme has a deep black background regardless of the `style` tag shiki generate). I've removed it in my fork.

The trade-off boils down to this I believe:

A user can choose a "best fit" theme from the pre-existing shiki-options, colors won't match perfectly. Works "as is" in this PR (if the `code` background property is removed)

vs 

A lot of custom code, and a knowledge of syntax highlighting in VSCode Themes, to generate a shiki theme on the fly; along with updates to the gatsby-remark-shiki plugin, and potential `gatsby-mdx`

All the best,

Jon

**Comment by mlent** [comment]
Hm that's a bummer that the gatsby plugin doesn't expose that. I wonder exactly what the purpose of using the plugin is vs. just using the library directly?

I will have to look into that next week then, thanks for your patience!

**Comment by jonsherrard** [comment]
Just to give you an insight into how complex syntax highlighting themes can be: 

https://github.com/octref/shiki/blob/master/packages/themes/data/material/Material-Theme-Default.json

No trying to put you off, but it is a big task! And a very complex one to configure in user land too. For example, which of my theme values apply to which of those myriad highlighting options etc.

I'd venture that most of the _value_ of a syntax highlight is down to the ease of read/parse ability for a human, rather than it matching the site-theme directly. Good luck either way :)

**Comment by mlent** [comment]
Yeah! I know it's complex, at least based on some vim themes I've done light customization on. But it would at least be nice to find something that somewhat fits into the bright theme colors that come with it.

Thanks for the reference code! That's really helpful. Let's see, at least for my purposes, there is very little code in my Help Center, so it doesn't matter hugely what it looks like.

**Pull request merged**
